### PR TITLE
Tinycc 65816 0.9.25

### PR DESCRIPTION
**Pull request by kobenairb**
And the last for today, the 0.9.25 version. The 26 is in progress...

### CODE REVIEW

**Comment by alekmaul** [comment]
nice ! what about the other PR on pvsneslib branch ? do we need to close it ?

**Comment by kobenairb** [comment]
Yes sure ! it's irrelevant now that we have a dedicated repository. ~Close it please~. [DONE]

By the way,

 * Can you also create the following branches ? I will update my PR on them respectively.
     -  tinycc-65816-0.9.23
     - tinycc-65816-0.9.24
     - tinycc-65816-0.9.25

 * Can you rename the repository name to tcc-65816 as for pvsneslib ? it's not mandatory but it's more clear :)
 
 ~I add directly a new PR with our current tcc-816 version (same as pvsneslib) to main, just to check the new configuration with submodules.~ [DONE]

 > Tell me if I'm wrong but I believe we'll have to update the following libraries between each tcc update:

 From 
```
compiler/tcc-65816/include/ctype.h
compiler/tcc-65816/include/float.h
compiler/tcc-65816/include/limits.h
compiler/tcc-65816/include/math.h
compiler/tcc-65816/include/setjmp.h
compiler/tcc-65816/include/stdarg.h
compiler/tcc-65816/include/stddef.h
compiler/tcc-65816/include/stdint.h
compiler/tcc-65816/include/strings.h
compiler/tcc-65816/include/stdbool.h
compiler/tcc-65816/include/stdio.h
compiler/tcc-65816/include/stdlib.h
compiler/tcc-65816/include/string.h
```
To
```
devkitsnes/include/ctype.h
devkitsnes/include/float.h
devkitsnes/include/limits.h
devkitsnes/include/math.h
devkitsnes/include/setjmp.h
devkitsnes/include/stdint.h
devkitsnes/include/strings.h
devkitsnes/include/stdarg.h
devkitsnes/include/stdbool.h
devkitsnes/include/stddef.h
devkitsnes/include/stdio.h
devkitsnes/include/stdlib.h
devkitsnes/include/string.h
```

**Comment by RetroAntho** [comment]
Hi,

Why do you need a branch for each version?
As we would like to upgrade until the latest version, i do not think it make sense to keep a branch for each version because we will not update it anymore.
If it is only to keep history, the commits you did should be enough.

i confirm that the devkitsnes include comes from tcc. It should be aligned and we could add a rule in tcc makefile (the one in compiler folder) to update devkitsnes as compilation step

**Comment by alekmaul** [comment]
I think we will a branch for each version to be able to come back to a specific branch if a defect is detected.
We can also do some "cherry pick" to go back to a specific commit. It's on your side to decide if we need a specific branch or just a brnach to current update

**Comment by RetroAntho** [comment]
Yes, it is only related to habits.
So, let's go for a branch for each version and we will clean it in the future if needed (or when the last version will be full functional).
@kobenairb thanks for these improvements, everything is merged now. Feel free to submit other PR and upgrade tcc again :)

See you soon !

**Comment by RetroAntho** [comment]
hi @kobenairb 
Do you still plan to upgrade the code to latest version?
To automate build of pvsneslib, we will need a tcc version which works in 64b soon.
If you think you will works on it in the coming month, we will do more tests with the latest version to move definitively pvsneslib on it.

**Comment by kobenairb** [comment]
hi @alekmaul,

Yes for sure, I was very busy the last days but I continue slowly to upgrade to the 0.9.26 version which is a big work as it's almost 3 years of commits. I create a PR for the 0.9.26 today but it's not finished (I mean I didn't add all the commits yet). But it's maybe a better version that the 0.9.25 ... I'll let you check. By the way I'd also worked on the 816-opt python script to port it in C language. I hope to finish it for next week (here https://github.com/kobenairb/opt-65816).

I'll back to the tcc migration this weekend and will try to finish the 0.9.26 version before the end of the month.

Regards, Brian.

**Comment by RetroAntho** [comment]
It is not Alekmaul :)
Great news, i will check and validate your PR for the end of the week :)
Do you have an email or discord account to discuss quickly (or easier than using github) ?
I checked your repository for python part and i can give you more informations to update the readme (python script is not created by narno, tcc port not developed by alekmaul :) )

**Comment by kobenairb** [comment]
Hi RetroAntho,

My bad, and sorry to not be focus when I reply you.

"python script is not created by narno, tcc port not developed by alekmaul" I feel so stupid here ;p So you'll tell me how and what to add for the acknowledgements, because I just port something already made. I keep you informed when I'm done on this project, my goal is first to use and test it as it and then add it directly in tcc (maybe on the fly, or by providing an argument).

Here is my email : kobenairb@gmail.com
And my discord : k0b3Na1rb#5682

Brian.

**Comment by RetroAntho** [comment]
Hi @kobenairb ,

no problem, do not worry :) it is not stupid, it become really hard to find history because these tools become old.
Now everything is in github, it will be more easy to track changes and contributors !

I will contact you by discord soon :)

**Pull request merged**
